#!/bin/bash

MACHINE_TYPE=`uname -m`

if [ "${MACHINE_TYPE}" = 'x86_64' ]; then
  MACHINE_TAG=
elif [ "${MACHINE_TYPE}" = armv7l ]; then
  MACHINE_TAG=':arm32v7'
else
  echo "Architecture not supported: $MACHINE_TYPE" 1>&2
  exit 1
fi

if [ -z "$DATA_DIR" ]; then
  DATA_DIR="$(pwd)/data"
fi

cd "$(dirname "$0")" || exit 1	# bash prints a message if dir not found.

docker run -ti --rm --net host -v "$DATA_DIR":/data "networkboot/dhcpd${MACHINE_TAG}" "$@"

